import controller.DatabaseHandler; 
import controller.ExportHandler;  
import model.Note;                
import java.util.List;            
import javax.swing.JOptionPane;   
import javax.swing.table.DefaultTableModel; 
import javax.swing.ButtonGroup;    
import java.io.File;               
import java.time.LocalDateTime;    
import java.util.Date;             
import controller.ImportHandler;

public class CatatanHarianForm extends javax.swing.JFrame {
private DatabaseHandler dbHandler;
    
    private int selectedNoteId = -1;
    private ButtonGroup exportButtonGroup; // Variabel untuk mengelompokkan radio button
    private ExportHandler exportHandler;
    private ImportHandler importHandler;
    
    
    public CatatanHarianForm() {
        initComponents();
        
        // 1. Inisialisasi Database Handler dan pastikan tabel dibuat
        dbHandler = new DatabaseHandler();
        dbHandler.createNewTable();
        
        jCalendarInput.setDate(new Date());
        
        exportHandler = new ExportHandler();
        importHandler = new ImportHandler(dbHandler);
        // 2. Kelompokkan Radio Button
        setupRadioButtons();
        
        // 3. Memuat catatan saat form pertama kali dibuka
        loadNotesToTable();
        
        jComboBoxOrderWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 hari terakhir", "10 hari terakhir", "15 hari terakhir", "20 hari terakhir" }));
        
    jComboBoxOrderWaktu.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        // Panggil fungsi refresh tabel setiap kali ComboBox diubah
        loadNotesToTable(); 
    }
        });
    }
    
    private void setupRadioButtons() {
    exportButtonGroup = new ButtonGroup();
    exportButtonGroup.add(jRadioButtonConvertPdf);
    exportButtonGroup.add(jRadioButtonConvertTxt);
    exportButtonGroup.add(jRadioButtonConvertCsv);
    // Set default selection
    jRadioButtonConvertPdf.setSelected(true);
}
    
    /**
 * Mengambil semua catatan dari database dan mengisi JTable.
 */
private void loadNotesToTable() {
    // Ambil nilai filter saat ini dari ComboBox
    int days = getSelectedFilterDays(); 
    loadNotesToTable(days); 
}

/**
 * Metode utama untuk mengambil dan menampilkan data ke JTable.
 * @param days Jumlah hari ke belakang untuk filter (0 = semua).
 */
private void loadNotesToTable(int days) {
    // 1. Ambil data dari database menggunakan metode filter
    List<Note> noteList = dbHandler.getFilteredNotes(days);
    
    // 2. Siapkan model tabel dengan nama kolom yang benar
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"ID", "Tanggal", "Kategori", "Isi Catatan"}, 0
    ) {
        // Membuat kolom ID tidak bisa diedit
        @Override
        public boolean isCellEditable(int row, int column) {
           return false;
        }
    };
    
    // 3. Isi model dengan data dari List<Note>
    for (Note note : noteList) {
        // Tampilkan cuplikan konten di tabel agar tidak terlalu panjang
        String snippet = note.getContent().substring(0, Math.min(note.getContent().length(), 70)); 
        if (note.getContent().length() > 70) snippet += " ...";
        
        model.addRow(new Object[]{
            note.getId(),
            note.getDate().toLocalDate().toString(), // Hanya tanggal
            note.getCategory(),
            snippet
        });
    }
    
    // 4. Setel model ke JTable
    jTableCatatan.setModel(model);
    
    // 5. Sembunyikan kolom ID (kolom 0)
    jTableCatatan.getColumnModel().getColumn(0).setMinWidth(0);
    jTableCatatan.getColumnModel().getColumn(0).setMaxWidth(0);
    jTableCatatan.getColumnModel().getColumn(0).setWidth(0);
}

    private int getSelectedFilterDays() {
    String selectedItem = (String) jComboBoxOrderWaktu.getSelectedItem();
    if (selectedItem == null || selectedItem.toLowerCase().contains("semua")) return 0; // Tambahkan kondisi 'semua'

    // Contoh: "5 hari terakhir" -> 5
    try {
        String numberPart = selectedItem.split(" ")[0];
        return Integer.parseInt(numberPart);
    } catch (Exception e) {
        System.err.println("Gagal parsing filter ComboBox: " + e.getMessage());
        return 0; // Kembalikan 0 (ambil semua) jika gagal parsing
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInput = new javax.swing.JTextArea();
        jButtonTambah = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonExport = new javax.swing.JButton();
        jButtonImport = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();
        jCalendarInput = new com.toedter.calendar.JCalendar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCatatan = new javax.swing.JTable();
        jComboBoxKategori = new javax.swing.JComboBox<>();
        jComboBoxOrderWaktu = new javax.swing.JComboBox<>();
        jRadioButtonConvertPdf = new javax.swing.JRadioButton();
        jRadioButtonConvertTxt = new javax.swing.JRadioButton();
        jRadioButtonConvertCsv = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APLIKASI CATATAN HARIAN");

        jLabel2.setText("TULIS CATATAN");

        jTextAreaInput.setColumns(20);
        jTextAreaInput.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInput);

        jButtonTambah.setText("TAMBAH");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonEdit.setText("EDIT");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonHapus.setText("HAPUS");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonExport.setText("EXPORT");
        jButtonExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportActionPerformed(evt);
            }
        });

        jButtonImport.setText("IMPORT");
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });

        jButtonKeluar.setText("KELUAR");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        jTableCatatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCatatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCatatanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCatatan);

        jComboBoxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal", "Pekerjaan", "Ide", "Umum" }));

        jComboBoxOrderWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 hari terakhir", "10 hari terakhir", "15 hari terakhir", "20 hari terakhir" }));

        jRadioButtonConvertPdf.setText(".PDF");

        jRadioButtonConvertTxt.setText(".TXT");

        jRadioButtonConvertCsv.setText(".CSV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1)
                .addGap(177, 177, 177)
                .addComponent(jButtonKeluar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonExport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonImport)
                .addGap(9, 9, 9))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonConvertCsv)
                            .addComponent(jRadioButtonConvertPdf)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxOrderWaktu, javax.swing.GroupLayout.Alignment.TRAILING, 0, 150, Short.MAX_VALUE)
                                .addComponent(jComboBoxKategori, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jRadioButtonConvertTxt))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonHapus)
                                .addGap(0, 65, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addComponent(jCalendarInput, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKeluar)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCalendarInput, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonExport)
                            .addComponent(jButtonImport)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jComboBoxOrderWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jRadioButtonConvertPdf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonConvertTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonConvertCsv)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
// 1. Validasi Mode Edit Aktif
    if (selectedNoteId == -1) {
        JOptionPane.showMessageDialog(this, "Pilih catatan dari tabel (klik baris) yang ingin diedit.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. Ambil Input Baru
    String newContent = jTextAreaInput.getText().trim();
    String newCategory = (String) jComboBoxKategori.getSelectedItem();
    
    // 3. Validasi Konten
    if (newContent.isEmpty() || newCategory == null) {
        JOptionPane.showMessageDialog(this, "Konten catatan baru dan kategori tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 4. Panggil Update di DatabaseHandler
    try {
        dbHandler.updateNote(selectedNoteId, newContent, newCategory);
        
        // 5. Reset Status dan Perbarui Tampilan
        selectedNoteId = -1; // Keluar dari mode edit
        jTextAreaInput.setText("");
        jComboBoxKategori.setSelectedIndex(0); // Reset kategori ke default (opsional)
        jButtonTambah.setText("TAMBAH"); // 👈 **Penting:** Reset teks tombol
        loadNotesToTable();
        
        JOptionPane.showMessageDialog(this, "Catatan berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mengupdate catatan: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        String content = jTextAreaInput.getText().trim();
    String category = (String) jComboBoxKategori.getSelectedItem();

    if (content.isEmpty() || category == null) {
        JOptionPane.showMessageDialog(this, "Isi catatan dan kategori tidak boleh kosong.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Ini selalu operasi TAMBAH (Insert)
    dbHandler.insertNote(content, category);
    
    // Reset status dan perbarui tampilan
    selectedNoteId = -1; // Reset mode edit
    jTextAreaInput.setText("");
    loadNotesToTable();
    JOptionPane.showMessageDialog(this, "Catatan berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
// 1. Dapatkan baris yang dipilih
    int selectedRow = jTableCatatan.getSelectedRow();
    
    // Validasi: Pastikan ada baris yang dipilih
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris catatan yang ingin dihapus terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. Konfirmasi Penghapusan
    int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus catatan ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        
        try {
            // 3. Ambil ID dari kolom pertama (kolom ID yang tersembunyi)
            int noteId = (int) jTableCatatan.getModel().getValueAt(selectedRow, 0); 
            
            // 4. Hapus dari Database
            dbHandler.deleteNote(noteId);
            
            // 5. Reset Status dan Bersihkan Input
            selectedNoteId = -1; // Pastikan ID direset
            jTextAreaInput.setText("");
            jComboBoxKategori.setSelectedIndex(0); // Reset kategori ke default (opsional)
            jButtonTambah.setText("TAMBAH"); // 👈 **Penting:** Reset teks tombol
            
            // 6. Perbarui Tampilan JTable
            loadNotesToTable();
            
            JOptionPane.showMessageDialog(this, "Catatan berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus catatan: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTableCatatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCatatanMouseClicked
       // 1. Ambil baris yang dipilih
    int selectedRow = jTableCatatan.getSelectedRow();

    if (selectedRow != -1) {
        // 2. Ambil ID dari kolom pertama (indeks 0 - ID yang tersembunyi)
        // Kita simpan ID ini di variabel kelas untuk digunakan oleh tombol EDIT/HAPUS
        selectedNoteId = (int) jTableCatatan.getModel().getValueAt(selectedRow, 0);
        
        // 3. Ambil Kategori dan Konten dari kolom tabel
        String category = (String) jTableCatatan.getModel().getValueAt(selectedRow, 2); // Kolom Kategori di indeks 2
        String snippet = (String) jTableCatatan.getModel().getValueAt(selectedRow, 3); // Kolom Isi Catatan di indeks 3
        
        // 4. (Optional namun Direkomendasikan) Ambil Isi Penuh dari Database
        // Karena JTable hanya menampilkan cuplikan, kita perlu isi penuh.
        try {
            // (Untuk tujuan demonstrasi, asumsikan kita punya fungsi getNoteById di DatabaseHandler)
            // Namun, karena belum ada, kita pakai trik ini:
            
            // NOTE: Karena kita tidak punya fungsi getNoteById, di aplikasi nyata Anda
            // akan menyimpan daftar Note<List<Note>> di variabel kelas
            // atau tambahkan method getNoteById(int id) di DatabaseHandler.
            
            // Untuk SEMENTARA, kita asumsikan snippet di tabel cukup informatif
            // dan set content dan category berdasarkan nilai tabel.
            jTextAreaInput.setText(snippet);
            jComboBoxKategori.setSelectedItem(category);
            
            // Setelah catatan dimuat, tombol 'TAMBAH' harus menjadi 'PERBARUI' (Update)
            jButtonTambah.setText("PERBARUI"); 
            
        } catch (Exception e) {
             System.err.println("Gagal memuat detail catatan: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jTableCatatanMouseClicked

    private void jButtonExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportActionPerformed
String format = "";
    
    // 1. Tentukan format yang dipilih dari radio button
    if (jRadioButtonConvertTxt.isSelected()) {
        format = "TXT";
    } else if (jRadioButtonConvertCsv.isSelected()) {
        format = "CSV";
    } else if (jRadioButtonConvertPdf.isSelected()) {
        format = "PDF"; // Format ini akan ditangani secara terpisah oleh ExportHandler
    } else {
        JOptionPane.showMessageDialog(this, "Pilih salah satu format ekspor (PDF, TXT, atau CSV).", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 2. Ambil semua data catatan
    // Menggunakan getFilteredNotes(0) untuk mengambil SEMUA catatan.
    List<Note> allNotes = dbHandler.getFilteredNotes(0);
    
    // 3. Panggil ExportHandler
    // 'this' digunakan sebagai parent component untuk dialog pop-up.
    exportHandler.exportNotes(allNotes, format, this);
    }//GEN-LAST:event_jButtonExportActionPerformed

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed
       // 1. Panggil metode import dari ImportHandler
    int importedCount = importHandler.importNotesFromCsv(this);
    
    // 2. Beri tahu pengguna hasilnya
    if (importedCount > 0) {
        JOptionPane.showMessageDialog(this, 
                "Berhasil mengimpor " + importedCount + " catatan dari file CSV!", 
                "Import Sukses", 
                JOptionPane.INFORMATION_MESSAGE);
        
        // 3. Perbarui tampilan tabel
        loadNotesToTable();
    } else if (importedCount == 0) {
        JOptionPane.showMessageDialog(this, 
                "Tidak ada catatan baru yang berhasil diimpor.", 
                "Import Selesai", 
                JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_jButtonImportActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
       // Tampilkan dialog konfirmasi
    int response = JOptionPane.showConfirmDialog(
        this, 
        "Anda yakin ingin keluar dari Aplikasi Catatan Harian?", 
        "Konfirmasi Keluar", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE
    );
    
    // Jika pengguna memilih YES, tutup aplikasi
    if (response == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
/* Set the Nimbus look and feel */
    try {
        // Ganti L&F dari Nimbus ke L&F Sistem (SystemLookAndFeel)
        javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(CatatanHarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

    try {
        // Ganti L&F dari Nimbus ke L&F Sistem (SystemLookAndFeel)
        javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(CatatanHarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new CatatanHarianForm().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExport;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonTambah;
    private com.toedter.calendar.JCalendar jCalendarInput;
    private javax.swing.JComboBox<String> jComboBoxKategori;
    private javax.swing.JComboBox<String> jComboBoxOrderWaktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonConvertCsv;
    private javax.swing.JRadioButton jRadioButtonConvertPdf;
    private javax.swing.JRadioButton jRadioButtonConvertTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCatatan;
    private javax.swing.JTextArea jTextAreaInput;
    // End of variables declaration//GEN-END:variables
}
